global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['seattle-container:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
